In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/vegtablae-2023/sample_submission.csv
/kaggle/input/vegtablae-2023/train.csv
/kaggle/input/vegtablae-2023/test.csv
/kaggle/input/vegtablae-2023/international_trade.csv

In [2]:
train = pd.read_csv('/kaggle/input/vegtablae-2023/train.csv')
test = pd.read_csv('/kaggle/input/vegtablae-2023/test.csv')
international_trade_df = pd.read_csv('/kaggle/input/vegtablae-2023/international_trade.csv')

In [3]:
display(train,test)

,ID,timestamp,item,corporation,location,supply(kg),price(원/kg)
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0
...,...,...,...,...,...,...,...
59392,RD_F_J_20230227,2023-02-27,RD,F,J,452440.0,468.0
59393,RD_F_J_20230228,2023-02-28,RD,F,J,421980.0,531.0
59394,RD_F_J_20230301,2023-03-01,RD,F,J,382980.0,574.0
59395,RD_F_J_20230302,2023-03-02,RD,F,J,477220.0,523.0
59396,RD_F_J_20230303,2023-03-03,RD,F,J,427520.0,529.0

                   ID   timestamp item corporation location
0     TG_A_J_20230304  2023-03-04   TG           A        J
1     TG_A_J_20230305  2023-03-05   TG           A        J
2     TG_A_J_20230306  2023-03-06   TG           A        J
3     TG_A_J_20230307  2023-03-07   TG           A        J
4     TG_A_J_20230308  2023-03-08   TG           A        J
...               ...         ...  ...         ...      ...
1087  RD_F_J_20230327  2023-03-27   RD           F        J
1088  RD_F_J_20230328  2023-03-28   RD           F        J
1089  RD_F_J_20230329  2023-03-29   RD           F        J
1090  RD_F_J_20230330  2023-03-30   RD           F        J
1091  RD_F_J_20230331  2023-03-31   RD           F        J

[1092 rows x 5 columns]

In [4]:
international_trade_df

,기간,품목명,수출 중량,수출 금액,수입 중량,수입 금액,무역수지
0,2019-01,토마토(신선한 것이나 냉장한 것으로 한정한다),356571,990,0,0,990
1,2019-01,양파,821330,222,4003206,1118,-896
2,2019-01,쪽파,60,1,93405,128,-127
3,2019-01,꽃양배추와 브로콜리(broccoli),160,1,638913,563,-562
4,2019-01,방울다다기 양배추,0,0,7580,38,-38
...,...,...,...,...,...,...,...
1269,2023-02,포포(papaw)[파파야(papaya)],0,0,23830,71,-71
1270,2023-02,사과,135165,351,0,0,351
1271,2023-02,배,2206012,5411,1,0,5411
1272,2023-02,신 체리[프루너스 체라서스(Prunus cerasus)],5,0,0,0,0
1273,2023-02,자두,0,0,2,0,0

In [5]:
!pip install autogluon

Collecting autogluon
  Obtaining dependency information for autogluon from https://files.pythonhosted.org/packages/2e/42/f26592ecf3dc4e4edcbc5f7f7e3deba25b0681fad2ad04a82d12af17e3a4/autogluon-0.8.2-py3-none-any.whl.metadata
  Downloading autogluon-0.8.2-py3-none-any.whl.metadata (11 kB)
Collecting autogluon.core[all]==0.8.2 (from autogluon)
  Obtaining dependency information for autogluon.core[all]==0.8.2 from https://files.pythonhosted.org/packages/e0/56/545adb1d388e78591cd7e36de0c8b889c1944de362bdaeec0f31d01890df/autogluon.core-0.8.2-py3-none-any.whl.metadata
  Downloading autogluon.core-0.8.2-py3-none-any.whl.metadata (12 kB)
Collecting autogluon.features==0.8.2 (from autogluon)
  Obtaining dependency information for autogluon.features==0.8.2 from https://files.pythonhosted.org/packages/bb/ea/7892719f78a30aee1bf42c4a0540fbae98bfbdf56b85fab79ffc437eb687/autogluon.features-0.8.2-py3-none-any.whl.metadata
  Downloading autogluon.features-0.8.2-py3-none-any.whl.metadata (11 kB)
Collecting autogluon.tabular[all]==0.8.2 (from autogluon)
  Obtaining dependency information for autogluon.tabular[all]==0.8.2 from https://files.pythonhosted.org/packages/f3/dc/0bd8cadb9a5e2f3e5b12caaa6745357d912ffc7b8b75fb4e426a38331028/autogluon.tabular-0.8.2-py3-none-any.whl.metadata
  Downloading autogluon.tabular-0.8.2-py3-none-any.whl.metadata (13 kB)
Collecting autogluon.multimodal==0.8.2 (from autogluon)
  Obtaining dependency information for autogluon.multimodal==0.8.2 from https://files.pythonhosted.org/packages/f4/df/a3921edb866555154d5a53adbcd2268fd3b53071820b6382f2619ad439f3/autogluon.multimodal-0.8.2-py3-none-any.whl.metadata
  Downloading autogluon.multimodal-0.8.2-py3-none-any.whl.metadata (13 kB)
Collecting autogluon.timeseries[all]==0.8.2 (from autogluon)
  Obtaining dependency information for autogluon.timeseries[all]==0.8.2 from https://files.pythonhosted.org/packages/50/38/1768d30684292d064dad4457355d6928581c5b832a3f65a6a023df2ff4ff/autogluon.timeseries-0.8.2-py3-none-any.whl.metadata
  Downloading autogluon.timeseries-0.8.2-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: numpy<1.27,>=1.21 in /opt/conda/lib/python3.10/site-packages (from autogluon.core[all]==0.8.2->autogluon) (1.24.3)
Requirement already satisfied: scipy<1.12,>=1.5.4 in /opt/conda/lib/python3.10/site-packages (from autogluon.core[all]==0.8.2->autogluon) (1.11.3)
Requirement already satisfied: scikit-learn<1.3,>=1.0 in /opt/conda/lib/python3.10/site-packages (from autogluon.core[all]==0.8.2->autogluon) (1.2.2)
Requirement already satisfied: networkx<4,>=3.0 in /opt/conda/lib/python3.10/site-packages (from autogluon.core[all]==0.8.2->autogluon) (3.1)
Collecting pandas<1.6,>=1.4.1 (from autogluon.core[all]==0.8.2->autogluon)
  Downloading pandas-1.5.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 61.0 MB/s eta 0:00:00
Requirement already satisfied: tqdm<5,>=4.38 in /opt/conda/lib/python3.10/site-packages (from autogluon.core[all]==0.8.2->autogluon) (4.66.1)
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from autogluon.core[all]==0.8.2->autogluon) (2.31.0)
Requirement already satisfied: matplotlib in /opt/conda/lib/python3.10/site-packages (from autogluon.core[all]==0.8.2->autogluon) (3.7.3)
Requirement already satisfied: boto3<2,>=1.10 in /opt/conda/lib/python3.10/site-packages (from autogluon.core[all]==0.8.2->autogluon) (1.26.100)
Collecting autogluon.common==0.8.2 (from autogluon.core[all]==0.8.2->autogluon)
  Obtaining dependency information for autogluon.common==0.8.2 from https://files.pythonhosted.org/packages/67/c7/aa2bd5708c9329a29245aa0cd955cace0662b92a82eb7605cf46b6e7e9d5/autogluon.common-0.8.2-py3-none-any.whl.metadata
  Downloading autogluon.common-0.8.2-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: hyperopt<0.2.8,>=0.2.7 in /opt/conda/lib/python3.10/site-packages (from autogluon.core[all]==0.8.2->autogluon) (0.2.7)
Collecting ray[default]<2.4,>=2.3 (from autogluon.core[all]==0.8.2->autogluon)
  Downloading ray-2.3.1-cp310-cp310-manylinux2014_x86_64.whl (58.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.5/58.5 MB 17.9 MB/s eta 0:00:00
Requirement already satisfied: pydantic<2.0,>=1.10.4 in /opt/conda/lib/python3.10/site-packages (from autogluon.core[all]==0.8.2->autogluon) (1.10.12)
Collecting grpcio<=1.50.0,>=1.42.0 (from autogluon.core[all]==0.8.2->autogluon)
  Downloading grpcio-1.50.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 70.2 MB/s eta 0:00:00
Collecting Pillow<9.6,>=9.3 (from autogluon.multimodal==0.8.2->autogluon)
  Downloading Pillow-9.5.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 68.4 MB/s eta 0:00:00
Collecting jsonschema<4.18,>=4.14 (from autogluon.multimodal==0.8.2->autogluon)
  Downloading jsonschema-4.17.3-py3-none-any.whl (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.4/90.4 kB 7.6 MB/s eta 0:00:00
Collecting seqeval<1.3.0,>=1.2.2 (from autogluon.multimodal==0.8.2->autogluon)
  Downloading seqeval-1.2.2.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 3.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... - \ | done
Collecting evaluate<0.4.0,>=0.2.2 (from autogluon.multimodal==0.8.2->autogluon)
  Downloading evaluate-0.3.0-py3-none-any.whl (72 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.9/72.9 kB 5.2 MB/s eta 0:00:00
Collecting accelerate<0.17,>=0.9 (from autogluon.multimodal==0.8.2->autogluon)
  Downloading accelerate-0.16.0-py3-none-any.whl (199 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.7/199.7 kB 14.1 MB/s eta 0:00:00
Requirement already satisfied: timm<0.10.0,>=0.9.2 in /opt/conda/lib/python3.10/site-packages (from autogluon.multimodal==0.8.2->autogluon) (0.9.10)
Collecting torch<1.14,>=1.9 (from autogluon.multimodal==0.8.2->autogluon)
  Downloading torch-1.13.1-cp310-cp310-manylinux1_x86_64.whl (887.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 887.5/887.5 MB 1.2 MB/s eta 0:00:00
Collecting torchvision<0.15.0 (from autogluon.multimodal==0.8.2->autogluon)
  Downloading torchvision-0.14.1-cp310-cp310-manylinux1_x86_64.whl (24.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.2/24.2 MB 36.5 MB/s eta 0:00:00
Collecting scikit-image<0.20.0,>=0.19.1 (from autogluon.multimodal==0.8.2->autogluon)
  Downloading scikit_image-0.19.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.9/13.9 MB 55.6 MB/s eta 0:00:00
Collecting pytorch-lightning<1.10.0,>=1.9.0 (from autogluon.multimodal==0.8.2->autogluon)
  Downloading pytorch_lightning-1.9.5-py3-none-any.whl (829 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 829.5/829.5 kB 41.3 MB/s eta 0:00:00
Requirement already satisfied: text-unidecode<1.4,>=1.3 in /opt/conda/lib/python3.10/site-packages (from autogluon.multimodal==0.8.2->autogluon) (1.3)
Collecting torchmetrics<0.12.0,>=0.11.0 (from autogluon.multimodal==0.8.2->autogluon)
  Downloading torchmetrics-0.11.4-py3-none-any.whl (519 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 519.2/519.2 kB 28.4 MB/s eta 0:00:00
Collecting transformers[sentencepiece]<4.27.0,>=4.23.0 (from autogluon.multimodal==0.8.2->autogluon)
  Downloading transformers-4.26.1-py3-none-any.whl (6.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 24.2 MB/s eta 0:00:00
Collecting nptyping<2.5.0,>=1.4.4 (from autogluon.multimodal==0.8.2->autogluon)
  Downloading nptyping-2.4.1-py3-none-any.whl (36 kB)
Collecting omegaconf<2.3.0,>=2.1.1 (from autogluon.multimodal==0.8.2->autogluon)
  Downloading omegaconf-2.2.3-py3-none-any.whl (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.3/79.3 kB 245.6 kB/s eta 0:00:00
Collecting pytorch-metric-learning<2.0,>=1.3.0 (from autogluon.multimodal==0.8.2->autogluon)
  Downloading pytorch_metric_learning-1.7.3-py3-none-any.whl (112 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.2/112.2 kB 275.3 kB/s eta 0:00:00
Collecting nlpaug<1.2.0,>=1.1.10 (from autogluon.multimodal==0.8.2->autogluon)
  Downloading nlpaug-1.1.11-py3-none-any.whl (410 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.5/410.5 kB 3.7 MB/s eta 0:00:00
Collecting nltk<4.0.0,>=3.4.5 (from autogluon.multimodal==0.8.2->autogluon)
  Downloading nltk-3.8.1-py3-none-any.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 4.2 MB/s eta 0:00:00
Collecting openmim<0.4.0,>=0.3.7 (from autogluon.multimodal==0.8.2->autogluon)
  Obtaining dependency information for openmim<0.4.0,>=0.3.7 from https://files.pythonhosted.org/packages/00/b3/95531cee452028869d0e08974561f83e9c256c98f62c7a45a51893a61c54/openmim-0.3.9-py2.py3-none-any.whl.metadata
  Downloading openmim-0.3.9-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: defusedxml<0.7.2,>=0.7.1 in /opt/conda/lib/python3.10/site-packages (from autogluon.multimodal==0.8.2->autogluon) (0.7.1)
Requirement already satisfied: jinja2<3.2,>=3.0.3 in /opt/conda/lib/python3.10/site-packages (from autogluon.multimodal==0.8.2->autogluon) (3.1.2)
Requirement already satisfied: tensorboard<3,>=2.9 in /opt/conda/lib/python3.10/site-packages (from autogluon.multimodal==0.8.2->autogluon) (2.13.0)
Requirement already satisfied: pytesseract<0.3.11,>=0.3.9 in /opt/conda/lib/python3.10/site-packages (from autogluon.multimodal==0.8.2->autogluon) (0.3.10)
Requirement already satisfied: lightgbm<3.4,>=3.3 in /opt/conda/lib/python3.10/site-packages (from autogluon.tabular[all]==0.8.2->autogluon) (3.3.2)
Collecting xgboost<1.8,>=1.6 (from autogluon.tabular[all]==0.8.2->autogluon)
  Obtaining dependency information for xgboost<1.8,>=1.6 from https://files.pythonhosted.org/packages/8c/3a/c9c5d4d5c49b132ef15ac7b5ccf56ef1c82efe36cd19414771762e97c00e/xgboost-1.7.6-py3-none-manylinux2014_x86_64.whl.metadata
  Downloading xgboost-1.7.6-py3-none-manylinux2014_x86_64.whl.metadata (1.9 kB)
Requirement already satisfied: fastai<2.8,>=2.3.1 in /opt/conda/lib/python3.10/site-packages (from autogluon.tabular[all]==0.8.2->autogluon) (2.7.13)
Requirement already satisfied: catboost<1.3,>=1.1 in /opt/conda/lib/python3.10/site-packages (from autogluon.tabular[all]==0.8.2->autogluon) (1.2.2)
Requirement already satisfied: joblib<2,>=1.1 in /opt/conda/lib/python3.10/site-packages (from autogluon.timeseries[all]==0.8.2->autogluon) (1.3.2)
Requirement already satisfied: statsmodels<0.15,>=0.13.0 in /opt/conda/lib/python3.10/site-packages (from autogluon.timeseries[all]==0.8.2->autogluon) (0.14.0)
Collecting gluonts<0.14,>=0.13.1 (from autogluon.timeseries[all]==0.8.2->autogluon)
  Obtaining dependency information for gluonts<0.14,>=0.13.1 from https://files.pythonhosted.org/packages/c9/da/2998c429adea79183f3e41bda4f3c44fc25404516c3da3a25da8c0bdf325/gluonts-0.13.8-py3-none-any.whl.metadata
  Downloading gluonts-0.13.8-py3-none-any.whl.metadata (9.4 kB)
Collecting statsforecast<1.5,>=1.4.0 (from autogluon.timeseries[all]==0.8.2->autogluon)
  Downloading statsforecast-1.4.0-py3-none-any.whl (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.0/92.0 kB 8.0 MB/s eta 0:00:00
Collecting mlforecast<0.7.4,>=0.7.0 (from autogluon.timeseries[all]==0.8.2->autogluon)
  Obtaining dependency information for mlforecast<0.7.4,>=0.7.0 from https://files.pythonhosted.org/packages/83/f0/fe8f0da0626fef11f7adf1c013ca185d00cd1bb967f39253bffc6a036c26/mlforecast-0.7.3-py3-none-any.whl.metadata
  Downloading mlforecast-0.7.3-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: ujson<6,>=5 in /opt/conda/lib/python3.10/site-packages (from autogluon.timeseries[all]==0.8.2->autogluon) (5.8.0)
Requirement already satisfied: psutil<6,>=5.7.3 in /opt/conda/lib/python3.10/site-packages (from autogluon.common==0.8.2->autogluon.core[all]==0.8.2->autogluon) (5.9.3)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.10/site-packages (from autogluon.common==0.8.2->autogluon.core[all]==0.8.2->autogluon) (68.1.2)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from accelerate<0.17,>=0.9->autogluon.multimodal==0.8.2->autogluon) (21.3)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.10/site-packages (from accelerate<0.17,>=0.9->autogluon.multimodal==0.8.2->autogluon) (6.0.1)
Collecting botocore<1.30.0,>=1.29.100 (from boto3<2,>=1.10->autogluon.core[all]==0.8.2->autogluon)
  Obtaining dependency information for botocore<1.30.0,>=1.29.100 from https://files.pythonhosted.org/packages/46/20/e7a9a8e6746872afcc4e3ad5ab503702c38813b3a532df27cce95c98b8cb/botocore-1.29.165-py3-none-any.whl.metadata
  Downloading botocore-1.29.165-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.10/site-packages (from boto3<2,>=1.10->autogluon.core[all]==0.8.2->autogluon) (1.0.1)
Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in /opt/conda/lib/python3.10/site-packages (from boto3<2,>=1.10->autogluon.core[all]==0.8.2->autogluon) (0.6.2)
Requirement already satisfied: graphviz in /opt/conda/lib/python3.10/site-packages (from catboost<1.3,>=1.1->autogluon.tabular[all]==0.8.2->autogluon) (0.20.1)
Requirement already satisfied: plotly in /opt/conda/lib/python3.10/site-packages (from catboost<1.3,>=1.1->autogluon.tabular[all]==0.8.2->autogluon) (5.16.1)
Requirement already satisfied: six in /opt/conda/lib/python3.10/site-packages (from catboost<1.3,>=1.1->autogluon.tabular[all]==0.8.2->autogluon) (1.16.0)
Requirement already satisfied: datasets>=2.0.0 in /opt/conda/lib/python3.10/site-packages (from evaluate<0.4.0,>=0.2.2->autogluon.multimodal==0.8.2->autogluon) (2.1.0)
Requirement already satisfied: dill in /opt/conda/lib/python3.10/site-packages (from evaluate<0.4.0,>=0.2.2->autogluon.multimodal==0.8.2->autogluon) (0.3.7)
Requirement already satisfied: xxhash in /opt/conda/lib/python3.10/site-packages (from evaluate<0.4.0,>=0.2.2->autogluon.multimodal==0.8.2->autogluon) (3.4.1)
Requirement already satisfied: multiprocess in /opt/conda/lib/python3.10/site-packages (from evaluate<0.4.0,>=0.2.2->autogluon.multimodal==0.8.2->autogluon) (0.70.15)
Requirement already satisfied: fsspec[http]>=2021.05.0 in /opt/conda/lib/python3.10/site-packages (from evaluate<0.4.0,>=0.2.2->autogluon.multimodal==0.8.2->autogluon) (2023.10.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /opt/conda/lib/python3.10/site-packages (from evaluate<0.4.0,>=0.2.2->autogluon.multimodal==0.8.2->autogluon) (0.17.3)
Requirement already satisfied: responses<0.19 in /opt/conda/lib/python3.10/site-packages (from evaluate<0.4.0,>=0.2.2->autogluon.multimodal==0.8.2->autogluon) (0.18.0)
Requirement already satisfied: pip in /opt/conda/lib/python3.10/site-packages (from fastai<2.8,>=2.3.1->autogluon.tabular[all]==0.8.2->autogluon) (23.2.1)
Requirement already satisfied: fastdownload<2,>=0.0.5 in /opt/conda/lib/python3.10/site-packages (from fastai<2.8,>=2.3.1->autogluon.tabular[all]==0.8.2->autogluon) (0.0.7)
Requirement already satisfied: fastcore<1.6,>=1.5.29 in /opt/conda/lib/python3.10/site-packages (from fastai<2.8,>=2.3.1->autogluon.tabular[all]==0.8.2->autogluon) (1.5.29)
Requirement already satisfied: fastprogress>=0.2.4 in /opt/conda/lib/python3.10/site-packages (from fastai<2.8,>=2.3.1->autogluon.tabular[all]==0.8.2->autogluon) (1.0.3)
Requirement already satisfied: spacy<4 in /opt/conda/lib/python3.10/site-packages (from fastai<2.8,>=2.3.1->autogluon.tabular[all]==0.8.2->autogluon) (3.7.2)
Requirement already satisfied: toolz~=0.10 in /opt/conda/lib/python3.10/site-packages (from gluonts<0.14,>=0.13.1->autogluon.timeseries[all]==0.8.2->autogluon) (0.12.0)
Requirement already satisfied: typing-extensions~=4.0 in /opt/conda/lib/python3.10/site-packages (from gluonts<0.14,>=0.13.1->autogluon.timeseries[all]==0.8.2->autogluon) (4.5.0)
Requirement already satisfied: future in /opt/conda/lib/python3.10/site-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==0.8.2->autogluon) (0.18.3)
Requirement already satisfied: cloudpickle in /opt/conda/lib/python3.10/site-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==0.8.2->autogluon) (2.2.1)
Requirement already satisfied: py4j in /opt/conda/lib/python3.10/site-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==0.8.2->autogluon) (0.10.9.7)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2<3.2,>=3.0.3->autogluon.multimodal==0.8.2->autogluon) (2.1.3)
Requirement already satisfied: attrs>=17.4.0 in /opt/conda/lib/python3.10/site-packages (from jsonschema<4.18,>=4.14->autogluon.multimodal==0.8.2->autogluon) (23.1.0)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 (from jsonschema<4.18,>=4.14->autogluon.multimodal==0.8.2->autogluon)
  Obtaining dependency information for pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 from https://files.pythonhosted.org/packages/d7/b7/64a125c488243965b7c5118352e47c6f89df95b4ac306d31cee409153d57/pyrsistent-0.20.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading pyrsistent-0.20.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (27 kB)
Requirement already satisfied: wheel in /opt/conda/lib/python3.10/site-packages (from lightgbm<3.4,>=3.3->autogluon.tabular[all]==0.8.2->autogluon) (0.41.2)
Requirement already satisfied: numba in /opt/conda/lib/python3.10/site-packages (from mlforecast<0.7.4,>=0.7.0->autogluon.timeseries[all]==0.8.2->autogluon) (0.57.1)
Collecting window-ops (from mlforecast<0.7.4,>=0.7.0->autogluon.timeseries[all]==0.8.2->autogluon)
  Downloading window_ops-0.0.14-py3-none-any.whl (14 kB)
Collecting gdown>=4.0.0 (from nlpaug<1.2.0,>=1.1.10->autogluon.multimodal==0.8.2->autogluon)
  Downloading gdown-4.7.1-py3-none-any.whl (15 kB)
Requirement already satisfied: click in /opt/conda/lib/python3.10/site-packages (from nltk<4.0.0,>=3.4.5->autogluon.multimodal==0.8.2->autogluon) (8.1.7)
Requirement already satisfied: regex>=2021.8.3 in /opt/conda/lib/python3.10/site-packages (from nltk<4.0.0,>=3.4.5->autogluon.multimodal==0.8.2->autogluon) (2023.8.8)
Collecting antlr4-python3-runtime==4.9.* (from omegaconf<2.3.0,>=2.1.1->autogluon.multimodal==0.8.2->autogluon)
  Downloading antlr4-python3-runtime-4.9.3.tar.gz (117 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.0/117.0 kB 9.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... - done
Requirement already satisfied: colorama in /opt/conda/lib/python3.10/site-packages (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==0.8.2->autogluon) (0.4.6)
Collecting model-index (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==0.8.2->autogluon)
  Downloading model_index-0.1.11-py3-none-any.whl (34 kB)
Collecting opendatalab (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==0.8.2->autogluon)
  Obtaining dependency information for opendatalab from https://files.pythonhosted.org/packages/10/82/28fa3a91b7c4852fbad9ad32c7b49e4b1e212ab7ccf7296736da0935070d/opendatalab-0.0.10-py3-none-any.whl.metadata
  Downloading opendatalab-0.0.10-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: rich in /opt/conda/lib/python3.10/site-packages (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==0.8.2->autogluon) (13.5.2)
Requirement already satisfied: tabulate in /opt/conda/lib/python3.10/site-packages (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==0.8.2->autogluon) (0.9.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/conda/lib/python3.10/site-packages (from pandas<1.6,>=1.4.1->autogluon.core[all]==0.8.2->autogluon) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas<1.6,>=1.4.1->autogluon.core[all]==0.8.2->autogluon) (2023.3)

In [6]:
from autogluon.timeseries import TimeSeriesDataFrame, TimeSeriesPredictor

In [7]:
train.head()

,ID,timestamp,item,corporation,location,supply(kg),price(원/kg)
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0

In [8]:
train['기간'] = train['timestamp'].str[:7]
train

,ID,timestamp,item,corporation,location,supply(kg),price(원/kg),기간
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0,2019-01
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0,2019-01
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0,2019-01
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0,2019-01
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0,2019-01
...,...,...,...,...,...,...,...,...
59392,RD_F_J_20230227,2023-02-27,RD,F,J,452440.0,468.0,2023-02
59393,RD_F_J_20230228,2023-02-28,RD,F,J,421980.0,531.0,2023-02
59394,RD_F_J_20230301,2023-03-01,RD,F,J,382980.0,574.0,2023-03
59395,RD_F_J_20230302,2023-03-02,RD,F,J,477220.0,523.0,2023-03
59396,RD_F_J_20230303,2023-03-03,RD,F,J,427520.0,529.0,2023-03

In [9]:
train['timestamp_tmp'] = pd.to_datetime(train['timestamp'])
train['Date'] = train['timestamp_tmp'].dt.strftime('%Y-%m')

In [10]:
sorted(international_trade_df['품목명'].unique())

['감귤',
 '결구(結球) 상추',
 '구아바(guava)',
 '그레이프프루트(grapefruit)와 포멜로(pomelo)',
 '꽃양배추와 브로콜리(broccoli)',
 '당근',
 '대추야자',
 '레몬[시트러스 리몬(Citrus limon)ㆍ시트러스 리머늄(Citrus limonum)]',
 '망고(mango)',
 '망고스틴(mangosteen)',
 '무화과',
 '방울다다기 양배추',
 '방울토마토',
 '배',
 '복숭아[넥터린(nectarine)을 포함한다]',
 '사과',
 '살구',
 '샬롯(shallot)',
 '수박',
 '순무',
 '신 체리[프루너스 체라서스(Prunus cerasus)]',
 '양배추',
 '양파',
 '오렌지',
 '오이류(신선한 것이나 냉장한 것으로 한정한다)',
 '완두[피섬 새티범(Pisum sativum)]',
 '위트루프 치커리(Witloof chicory)[시코리엄 인티부스 변종 포리오섬(Cichorium intybus var. foliosum)]',
 '자두',
 '쪽파',
 '참외',
 '콩[비그나(Vigna)속ㆍ파세러스(Phaseolus)속)]',
 '토마토(신선한 것이나 냉장한 것으로 한정한다)',
 '파인애플',
 '포포(papaw)[파파야(papaya)]']

In [11]:
from datetime import datetime
from dateutil.relativedelta import relativedelta
international_trade_df['기간'] = pd.to_datetime(international_trade_df['기간'])
# international_trade_df['Date_origin'] = international_trade_df['기간'].dt.strftime('%Y-%m')
# international_trade_df['Date'] = international_trade_df['기간'] + pd.DateOffset(months=1)
international_trade_df['Date'] = international_trade_df['기간'].dt.strftime('%Y-%m')

In [12]:
df_test = international_trade_df[international_trade_df.품목명.str.contains('감귤|브로콜리|무|당근|양배추')]
df_test

,기간,품목명,수출 중량,수출 금액,수입 중량,수입 금액,무역수지,Date
3,2019-01-01,꽃양배추와 브로콜리(broccoli),160,1,638913,563,-562,2019-01
4,2019-01-01,방울다다기 양배추,0,0,7580,38,-38,2019-01
5,2019-01-01,양배추,184650,94,395802,90,4,2019-01
8,2019-01-01,당근,23150,22,7466150,2955,-2934,2019-01
12,2019-01-01,무화과,2627,23,94529,464,-441,2019-01
...,...,...,...,...,...,...,...,...
1250,2023-02-01,양배추,13188,13,377456,104,-91,2023-02
1253,2023-02-01,당근,22510,20,9260020,3758,-3737,2023-02
1254,2023-02-01,순무,4000,4,2,0,4,2023-02
1258,2023-02-01,무화과,1319,14,104566,454,-440,2023-02
1264,2023-02-01,감귤,6895,34,27765,98,-64,2023-02

In [13]:
df_test["품목명"].value_counts()

품목명
꽃양배추와 브로콜리(broccoli)    50
방울다다기 양배추               50
양배추                     50
당근                      50
무화과                     50
감귤                      50
순무                       6
Name: count, dtype: int64

In [14]:
df_test.loc[df_test['품목명']=='꽃양배추와 브로콜리(broccoli)','품목명'] = '브로콜리'
df_test.loc[df_test['품목명']=='방울다다기 양배추','품목명'] = '양배추'
df_test.loc[df_test['품목명']=='순무','품목명'] = '무'
df_test = df_test[df_test['품목명']!='무화과']
df_test

             기간   품목명   수출 중량  수출 금액    수입 중량  수입 금액  무역수지     Date
3    2019-01-01  브로콜리     160      1   638913    563  -562  2019-01
4    2019-01-01   양배추       0      0     7580     38   -38  2019-01
5    2019-01-01   양배추  184650     94   395802     90     4  2019-01
8    2019-01-01    당근   23150     22  7466150   2955 -2934  2019-01
17   2019-01-01    감귤   58368    172        0      0   172  2019-01
...         ...   ...     ...    ...      ...    ...   ...      ...
1249 2023-02-01   양배추      71      1    10362     55   -55  2023-02
1250 2023-02-01   양배추   13188     13   377456    104   -91  2023-02
1253 2023-02-01    당근   22510     20  9260020   3758 -3737  2023-02
1254 2023-02-01     무    4000      4        2      0     4  2023-02
1264 2023-02-01    감귤    6895     34    27765     98   -64  2023-02

[256 rows x 8 columns]

In [15]:
fruits_dict = {'감귤':'TG' ,'브로콜리':'BC' ,'무':'RD' ,'당근':'CR' ,'양배추':'CB'}
fruits_dict

{'감귤': 'TG', '브로콜리': 'BC', '무': 'RD', '당근': 'CR', '양배추': 'CB'}

In [16]:
df_test['item'] = df_test['품목명'].map(fruits_dict)
df_test.drop(columns="품목명",inplace=True)

/tmp/ipykernel_20/2626899071.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['item'] = df_test['품목명'].map(fruits_dict)
/tmp/ipykernel_20/2626899071.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test.drop(columns="품목명",inplace=True)

In [17]:
df_test.groupby(["item","Date"]).mean()

                     기간      수출 중량   수출 금액     수입 중량   수입 금액    무역수지
item Date
BC   2019-01 2019-01-01      160.0     1.0  638913.0   563.0  -562.0
     2019-02 2019-02-01      780.0     1.0  396870.0   399.0  -398.0
     2019-03 2019-03-01      100.0     0.0  417756.0   503.0  -503.0
     2019-04 2019-04-01       18.0     0.0  783593.0  1207.0 -1207.0
     2019-05 2019-05-01       16.0     0.0  749745.0  1028.0 -1028.0
...                 ...        ...     ...       ...     ...     ...
TG   2022-10 2022-10-01    96813.0   118.0       0.0     0.0   118.0
     2022-11 2022-11-01  1382242.0  1406.0       0.0     0.0  1406.0
     2022-12 2022-12-01  1537517.0  1396.0   17600.0    22.0  1374.0
     2023-01 2023-01-01    81509.0   269.0       0.0     0.0   269.0
     2023-02 2023-02-01     6895.0    34.0   27765.0    98.0   -64.0

[206 rows x 6 columns]

In [18]:
train

,ID,timestamp,item,corporation,location,supply(kg),price(원/kg),기간,timestamp_tmp,Date
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0,2019-01,2019-01-01,2019-01
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0,2019-01,2019-01-02,2019-01
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0,2019-01,2019-01-03,2019-01
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0,2019-01,2019-01-04,2019-01
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0,2019-01,2019-01-05,2019-01
...,...,...,...,...,...,...,...,...,...,...
59392,RD_F_J_20230227,2023-02-27,RD,F,J,452440.0,468.0,2023-02,2023-02-27,2023-02
59393,RD_F_J_20230228,2023-02-28,RD,F,J,421980.0,531.0,2023-02,2023-02-28,2023-02
59394,RD_F_J_20230301,2023-03-01,RD,F,J,382980.0,574.0,2023-03,2023-03-01,2023-03
59395,RD_F_J_20230302,2023-03-02,RD,F,J,477220.0,523.0,2023-03,2023-03-02,2023-03
59396,RD_F_J_20230303,2023-03-03,RD,F,J,427520.0,529.0,2023-03,2023-03-03,2023-03

In [19]:
merged_df = pd.merge(left = train , right = df_test.groupby(["item","Date"]).mean(), how = "left", on = ["item","Date"],suffixes=['', '_right'])
merged_df

,ID,timestamp,item,corporation,location,supply(kg),price(원/kg),기간,timestamp_tmp,Date,기간_right,수출 중량,수출 금액,수입 중량,수입 금액,무역수지
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0,2019-01,2019-01-01,2019-01,2019-01-01,58368.0,172.0,0.0,0.0,172.0
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0,2019-01,2019-01-02,2019-01,2019-01-01,58368.0,172.0,0.0,0.0,172.0
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0,2019-01,2019-01-03,2019-01,2019-01-01,58368.0,172.0,0.0,0.0,172.0
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0,2019-01,2019-01-04,2019-01,2019-01-01,58368.0,172.0,0.0,0.0,172.0
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0,2019-01,2019-01-05,2019-01,2019-01-01,58368.0,172.0,0.0,0.0,172.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59392,RD_F_J_20230227,2023-02-27,RD,F,J,452440.0,468.0,2023-02,2023-02-27,2023-02,2023-02-01,4000.0,4.0,2.0,0.0,4.0
59393,RD_F_J_20230228,2023-02-28,RD,F,J,421980.0,531.0,2023-02,2023-02-28,2023-02,2023-02-01,4000.0,4.0,2.0,0.0,4.0
59394,RD_F_J_20230301,2023-03-01,RD,F,J,382980.0,574.0,2023-03,2023-03-01,2023-03,NaT,NaN,NaN,NaN,NaN,NaN
59395,RD_F_J_20230302,2023-03-02,RD,F,J,477220.0,523.0,2023-03,2023-03-02,2023-03,NaT,NaN,NaN,NaN,NaN,NaN
59396,RD_F_J_20230303,2023-03-03,RD,F,J,427520.0,529.0,2023-03,2023-03-03,2023-03,NaT,NaN,NaN,NaN,NaN,NaN

In [20]:
merged_df.fillna(0,inplace=True)

In [21]:
merged_df

,ID,timestamp,item,corporation,location,supply(kg),price(원/kg),기간,timestamp_tmp,Date,기간_right,수출 중량,수출 금액,수입 중량,수입 금액,무역수지
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0,2019-01,2019-01-01,2019-01,2019-01-01 00:00:00,58368.0,172.0,0.0,0.0,172.0
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0,2019-01,2019-01-02,2019-01,2019-01-01 00:00:00,58368.0,172.0,0.0,0.0,172.0
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0,2019-01,2019-01-03,2019-01,2019-01-01 00:00:00,58368.0,172.0,0.0,0.0,172.0
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0,2019-01,2019-01-04,2019-01,2019-01-01 00:00:00,58368.0,172.0,0.0,0.0,172.0
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0,2019-01,2019-01-05,2019-01,2019-01-01 00:00:00,58368.0,172.0,0.0,0.0,172.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59392,RD_F_J_20230227,2023-02-27,RD,F,J,452440.0,468.0,2023-02,2023-02-27,2023-02,2023-02-01 00:00:00,4000.0,4.0,2.0,0.0,4.0
59393,RD_F_J_20230228,2023-02-28,RD,F,J,421980.0,531.0,2023-02,2023-02-28,2023-02,2023-02-01 00:00:00,4000.0,4.0,2.0,0.0,4.0
59394,RD_F_J_20230301,2023-03-01,RD,F,J,382980.0,574.0,2023-03,2023-03-01,2023-03,0,0.0,0.0,0.0,0.0,0.0
59395,RD_F_J_20230302,2023-03-02,RD,F,J,477220.0,523.0,2023-03,2023-03-02,2023-03,0,0.0,0.0,0.0,0.0,0.0
59396,RD_F_J_20230303,2023-03-03,RD,F,J,427520.0,529.0,2023-03,2023-03-03,2023-03,0,0.0,0.0,0.0,0.0,0.0

In [22]:
train = merged_df[["ID","timestamp","item","corporation","location","supply(kg)","price(원/kg)","기간","Date","수출 중량","수출 금액","수입 중량","수입 금액","무역수지"]]
train

,ID,timestamp,item,corporation,location,supply(kg),price(원/kg),기간,Date,수출 중량,수출 금액,수입 중량,수입 금액,무역수지
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0,2019-01,2019-01,58368.0,172.0,0.0,0.0,172.0
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0,2019-01,2019-01,58368.0,172.0,0.0,0.0,172.0
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0,2019-01,2019-01,58368.0,172.0,0.0,0.0,172.0
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0,2019-01,2019-01,58368.0,172.0,0.0,0.0,172.0
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0,2019-01,2019-01,58368.0,172.0,0.0,0.0,172.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59392,RD_F_J_20230227,2023-02-27,RD,F,J,452440.0,468.0,2023-02,2023-02,4000.0,4.0,2.0,0.0,4.0
59393,RD_F_J_20230228,2023-02-28,RD,F,J,421980.0,531.0,2023-02,2023-02,4000.0,4.0,2.0,0.0,4.0
59394,RD_F_J_20230301,2023-03-01,RD,F,J,382980.0,574.0,2023-03,2023-03,0.0,0.0,0.0,0.0,0.0
59395,RD_F_J_20230302,2023-03-02,RD,F,J,477220.0,523.0,2023-03,2023-03,0.0,0.0,0.0,0.0,0.0
59396,RD_F_J_20230303,2023-03-03,RD,F,J,427520.0,529.0,2023-03,2023-03,0.0,0.0,0.0,0.0,0.0

In [23]:
train = train.replace({'TG':'감귤','BC':'꽃양배추와 브로콜리(broccoli)','RD':'순무','CR' : '당근','CB':'양배추'})
test = test.replace({'TG':'감귤','BC':'꽃양배추와 브로콜리(broccoli)','RD':'순무','CR' : '당근','CB':'양배추'})

In [24]:
train['item_id'] = train['ID'].str[:6]

# 날짜 변환
train['timestamp'] = pd.to_datetime(train['timestamp'])
test['timestamp'] = pd.to_datetime(test['timestamp'])

train['year'] = train['timestamp'].dt.year # 년도
train['month'] = train['timestamp'].dt.month # 월
train['day'] = train['timestamp'].dt.day # 일

test['year'] = test['timestamp'].dt.year # 년도
test['month'] = test['timestamp'].dt.month # 월
test['day'] = test['timestamp'].dt.day # 일


train['weekday'] = train['timestamp'].dt.weekday
test['weekday'] = test['timestamp'].dt.weekday

# Quarter 변수 생성
train['quarter'] = 0 # 겨울
train.loc[(train['month']>=3) & (train['month']<=5),'quarter']=1 # 봄
train.loc[(train['month']>=6) & (train['month']<=8),'quarter']=2 # 여름
train.loc[(train['month']>=9) & (train['month']<=11),'quarter']=3 # 가을

test['quarter'] = 0 # 겨울
test.loc[(test['month']>=3) & (test['month']<=5),'quarter']=1 # 봄
test.loc[(test['month']>=6) & (test['month']<=8),'quarter']=2 # 여름
test.loc[(test['month']>=9) & (test['month']<=11),'quarter']=3 # 가을

In [25]:
display(train,test)

,ID,timestamp,item,corporation,location,supply(kg),price(원/kg),기간,Date,수출 중량,수출 금액,수입 중량,수입 금액,무역수지,item_id,year,month,day,weekday,quarter
0,TG_A_J_20190101,2019-01-01,감귤,A,J,0.0,0.0,2019-01,2019-01,58368.0,172.0,0.0,0.0,172.0,TG_A_J,2019,1,1,1,0
1,TG_A_J_20190102,2019-01-02,감귤,A,J,0.0,0.0,2019-01,2019-01,58368.0,172.0,0.0,0.0,172.0,TG_A_J,2019,1,2,2,0
2,TG_A_J_20190103,2019-01-03,감귤,A,J,60601.0,1728.0,2019-01,2019-01,58368.0,172.0,0.0,0.0,172.0,TG_A_J,2019,1,3,3,0
3,TG_A_J_20190104,2019-01-04,감귤,A,J,25000.0,1408.0,2019-01,2019-01,58368.0,172.0,0.0,0.0,172.0,TG_A_J,2019,1,4,4,0
4,TG_A_J_20190105,2019-01-05,감귤,A,J,32352.0,1250.0,2019-01,2019-01,58368.0,172.0,0.0,0.0,172.0,TG_A_J,2019,1,5,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59392,RD_F_J_20230227,2023-02-27,순무,F,J,452440.0,468.0,2023-02,2023-02,4000.0,4.0,2.0,0.0,4.0,RD_F_J,2023,2,27,0,0
59393,RD_F_J_20230228,2023-02-28,순무,F,J,421980.0,531.0,2023-02,2023-02,4000.0,4.0,2.0,0.0,4.0,RD_F_J,2023,2,28,1,0
59394,RD_F_J_20230301,2023-03-01,순무,F,J,382980.0,574.0,2023-03,2023-03,0.0,0.0,0.0,0.0,0.0,RD_F_J,2023,3,1,2,1
59395,RD_F_J_20230302,2023-03-02,순무,F,J,477220.0,523.0,2023-03,2023-03,0.0,0.0,0.0,0.0,0.0,RD_F_J,2023,3,2,3,1
59396,RD_F_J_20230303,2023-03-03,순무,F,J,427520.0,529.0,2023-03,2023-03,0.0,0.0,0.0,0.0,0.0,RD_F_J,2023,3,3,4,1

,ID,timestamp,item,corporation,location,year,month,day,weekday,quarter
0,TG_A_J_20230304,2023-03-04,감귤,A,J,2023,3,4,5,1
1,TG_A_J_20230305,2023-03-05,감귤,A,J,2023,3,5,6,1
2,TG_A_J_20230306,2023-03-06,감귤,A,J,2023,3,6,0,1
3,TG_A_J_20230307,2023-03-07,감귤,A,J,2023,3,7,1,1
4,TG_A_J_20230308,2023-03-08,감귤,A,J,2023,3,8,2,1
...,...,...,...,...,...,...,...,...,...,...
1087,RD_F_J_20230327,2023-03-27,순무,F,J,2023,3,27,0,1
1088,RD_F_J_20230328,2023-03-28,순무,F,J,2023,3,28,1,1
1089,RD_F_J_20230329,2023-03-29,순무,F,J,2023,3,29,2,1
1090,RD_F_J_20230330,2023-03-30,순무,F,J,2023,3,30,3,1
1091,RD_F_J_20230331,2023-03-31,순무,F,J,2023,3,31,4,1

In [26]:
train.head()

,ID,timestamp,item,corporation,location,supply(kg),price(원/kg),기간,Date,수출 중량,수출 금액,수입 중량,수입 금액,무역수지,item_id,year,month,day,weekday,quarter
0,TG_A_J_20190101,2019-01-01,감귤,A,J,0.0,0.0,2019-01,2019-01,58368.0,172.0,0.0,0.0,172.0,TG_A_J,2019,1,1,1,0
1,TG_A_J_20190102,2019-01-02,감귤,A,J,0.0,0.0,2019-01,2019-01,58368.0,172.0,0.0,0.0,172.0,TG_A_J,2019,1,2,2,0
2,TG_A_J_20190103,2019-01-03,감귤,A,J,60601.0,1728.0,2019-01,2019-01,58368.0,172.0,0.0,0.0,172.0,TG_A_J,2019,1,3,3,0
3,TG_A_J_20190104,2019-01-04,감귤,A,J,25000.0,1408.0,2019-01,2019-01,58368.0,172.0,0.0,0.0,172.0,TG_A_J,2019,1,4,4,0
4,TG_A_J_20190105,2019-01-05,감귤,A,J,32352.0,1250.0,2019-01,2019-01,58368.0,172.0,0.0,0.0,172.0,TG_A_J,2019,1,5,5,0

명절/휴일 데이터 추가

In [27]:
import holidays
holiday_list = train.timestamp
holiday_list

0       2019-01-01
1       2019-01-02
2       2019-01-03
3       2019-01-04
4       2019-01-05
           ...
59392   2023-02-27
59393   2023-02-28
59394   2023-03-01
59395   2023-03-02
59396   2023-03-03
Name: timestamp, Length: 59397, dtype: datetime64[ns]

In [28]:
year_list = [2019,2020,2021,2022,2023]
kr_holiday = []
kr_myeongjul = []
myeongjul = ["Lunar New Year's Day","Chuseok"]
for arg in year_list:
    # 한국 휴일 객체 생성 
    kr_holidays = holidays.KR(arg)
    di = dict(kr_holidays)
    kr_holidays = {v:k for k,v in di.items()}
    
    tt=list(kr_holidays.keys())
    tt.remove("Lunar New Year's Day")
    tt.remove("Chuseok")
    hol = tt
    
    for arg_1 in myeongjul:
        kr_myeongjul.append(kr_holidays[arg_1])
    for arg_2 in hol:
        kr_holiday.append(kr_holidays[arg_2])
    
kr_myeongjul

[datetime.date(2019, 2, 5),
 datetime.date(2019, 9, 13),
 datetime.date(2020, 1, 25),
 datetime.date(2020, 10, 1),
 datetime.date(2021, 2, 12),
 datetime.date(2021, 9, 21),
 datetime.date(2022, 2, 1),
 datetime.date(2022, 9, 10),
 datetime.date(2023, 1, 22),
 datetime.date(2023, 9, 29)]

In [29]:
# list(kr_holidays.keys())

In [30]:
# tt=list(kr_holidays.keys())
# tt.remove("Lunar New Year's Day")
# tt.remove("Chuseok")
# tt

In [31]:
# holiday_list[0]

In [32]:
# holiday_list.apply(lambda x: 1 if x in kr_holidays else 0)

명절/휴일 데이터 생성

In [33]:
# generate holiday table
train['holiday'] = train.timestamp.apply(lambda x: 1 if x.date() in kr_myeongjul else (2 if x.date() in kr_holiday else 0))

In [34]:
train["holiday"].value_counts()

holiday
0    56355
2     2691
1      351
Name: count, dtype: int64

In [35]:
train.groupby("holiday")["price(원/kg)"].agg("mean")

holiday
0    1158.582504
1       0.000000
2     715.912300
Name: price(원/kg), dtype: float64

In [36]:
timeseries_data = TimeSeriesDataFrame(train.drop(columns=['ID','기간','corporation','location','item','Date']))

In [37]:
timeseries_data

                    supply(kg)  price(원/kg)    수출 중량  수출 금액  수입 중량  수입 금액  \
item_id timestamp
TG_A_J  2019-01-01         0.0          0.0  58368.0  172.0    0.0    0.0
        2019-01-02         0.0          0.0  58368.0  172.0    0.0    0.0
        2019-01-03     60601.0       1728.0  58368.0  172.0    0.0    0.0
        2019-01-04     25000.0       1408.0  58368.0  172.0    0.0    0.0
        2019-01-05     32352.0       1250.0  58368.0  172.0    0.0    0.0
...                        ...          ...      ...    ...    ...    ...
RD_F_J  2023-02-27    452440.0        468.0   4000.0    4.0    2.0    0.0
        2023-02-28    421980.0        531.0   4000.0    4.0    2.0    0.0
        2023-03-01    382980.0        574.0      0.0    0.0    0.0    0.0
        2023-03-02    477220.0        523.0      0.0    0.0    0.0    0.0
        2023-03-03    427520.0        529.0      0.0    0.0    0.0    0.0

                     무역수지  year  month  day  weekday  quarter  holiday
item_id timestamp
TG_A_J  2019-01-01  172.0  2019      1    1        1        0        2
        2019-01-02  172.0  2019      1    2        2        0        0
        2019-01-03  172.0  2019      1    3        3        0        0
        2019-01-04  172.0  2019      1    4        4        0        0
        2019-01-05  172.0  2019      1    5        5        0        0
...                   ...   ...    ...  ...      ...      ...      ...
RD_F_J  2023-02-27    4.0  2023      2   27        0        0        0
        2023-02-28    4.0  2023      2   28        1        0        0
        2023-03-01    0.0  2023      3    1        2        1        2
        2023-03-02    0.0  2023      3    2        3        1        0
        2023-03-03    0.0  2023      3    3        4        1        0

[59397 rows x 13 columns]

In [38]:
model = TimeSeriesPredictor(prediction_length = 28,target = 'price(원/kg)',eval_metric='RMSE')
model

No path specified. Models will be saved in: "AutogluonModels/ag-20231119_075747/"

In [39]:
model.fit(timeseries_data,random_seed = 42)

================ TimeSeriesPredictor ================
TimeSeriesPredictor.fit() called
Fitting with arguments:
{'enable_ensemble': True,
 'evaluation_metric': 'RMSE',
 'excluded_model_types': None,
 'hyperparameter_tune_kwargs': None,
 'hyperparameters': 'default',
 'num_val_windows': 1,
 'prediction_length': 28,
 'random_seed': 42,
 'target': 'price(원/kg)',
 'time_limit': None,
 'verbosity': 2}
Provided training data set with 59397 rows, 39 items (item = single time series). Average time series length is 1523.0. Data frequency is 'D'.
=====================================================
AutoGluon will save models to AutogluonModels/ag-20231119_075747/
AutoGluon will gauge predictive performance using evaluation metric: 'RMSE'
	This metric's sign has been flipped to adhere to being 'higher is better'. The reported score can be multiplied by -1 to get the metric value.

Provided dataset contains following columns:
	target:           'price(원/kg)'
	past covariates:  ['supply(kg)', '수출 중량', '수출 금액', '수입 중량', '수입 금액', '무역수지', 'year', 'month', 'day', 'weekday', 'quarter', 'holiday']

Starting training. Start time is 2023-11-19 07:57:47
Models that will be trained: ['Naive', 'SeasonalNaive', 'Theta', 'AutoETS', 'RecursiveTabular', 'DeepAR']
Training timeseries model Naive.
	-997.0634     = Validation score (-RMSE)
	0.12    s     = Training runtime
	11.98   s     = Validation (prediction) runtime
Training timeseries model SeasonalNaive.
	-843.9258     = Validation score (-RMSE)
	0.11    s     = Training runtime
	0.19    s     = Validation (prediction) runtime
Training timeseries model Theta.
	-838.8347     = Validation score (-RMSE)
	0.10    s     = Training runtime
	61.65   s     = Validation (prediction) runtime
Training timeseries model AutoETS.
	-797.0592     = Validation score (-RMSE)
	0.11    s     = Training runtime
	36.04   s     = Validation (prediction) runtime
Training timeseries model RecursiveTabular.
	-810.2125     = Validation score (-RMSE)
	10.61   s     = Training runtime
	2.21    s     = Validation (prediction) runtime
Training timeseries model DeepAR.
	-750.5122     = Validation score (-RMSE)
	456.88  s     = Training runtime
	2.10    s     = Validation (prediction) runtime
Fitting simple weighted ensemble.
	-712.6317     = Validation score (-RMSE)
	3.86    s     = Training runtime
	78.13   s     = Validation (prediction) runtime
Training complete. Models trained: ['Naive', 'SeasonalNaive', 'Theta', 'AutoETS', 'RecursiveTabular', 'DeepAR', 'WeightedEnsemble']
Total runtime: 587.80 s
Best model: WeightedEnsemble
Best model score: -712.6317

In [40]:
# -712.6053?, leaderboard : 686

In [41]:
result = model.predict(timeseries_data,random_seed=42)

Model not specified in predict, will default to the model with the best validation score: WeightedEnsemble

In [42]:
# 일반적인 시계열 점수는 후처리, 전처리 모두 활용해보기.

In [43]:
result

                           mean          0.1          0.2          0.3  \
item_id timestamp
TG_A_J  2023-03-04  3364.390663  1640.795532  2269.400768  2701.175892
        2023-03-05   582.941491 -1348.174708  -684.617541  -206.820005
        2023-03-06  3196.752489   235.847347  1282.824373  1993.167378
        2023-03-07  3591.196311   338.435898  1463.671205  2250.835375
        2023-03-08  3478.091449   -84.854669  1130.650946  2023.983532
...                         ...          ...          ...          ...
RD_F_J  2023-03-27   531.921919   -67.066291   165.343600   316.896491
        2023-03-28   553.457134   -79.718626   178.854083   327.683401
        2023-03-29   556.299801   -56.602913   175.437078   337.328354
        2023-03-30   547.540408  -112.926226   158.436256   316.422435
        2023-03-31   526.231542  -176.940171   144.741580   289.959373

                            0.4          0.5          0.6          0.7  \
item_id timestamp
TG_A_J  2023-03-04  3051.384004  3384.824730  3704.444975  4043.395946
        2023-03-05   198.875689   577.244906   958.598187  1366.274170
        2023-03-06  2575.742031  3111.783656  3672.362132  4299.074883
        2023-03-07  2925.208735  3547.140404  4167.437335  4811.827093
        2023-03-08  2751.454973  3418.763980  4128.344086  4859.783939
...                         ...          ...          ...          ...
RD_F_J  2023-03-27   435.485884   545.199045   654.302858   776.959128
        2023-03-28   447.499100   560.747535   672.812863   789.353328
        2023-03-29   455.231451   566.953596   677.994320   802.747807
        2023-03-30   434.424268   549.418556   666.845499   784.832916
        2023-03-31   414.781619   535.904813   649.946648   778.835851

                            0.8          0.9
item_id timestamp
TG_A_J  2023-03-04  4464.764305  5091.396313
        2023-03-05  1842.596886  2502.306460
        2023-03-06  5073.742837  6163.104927
        2023-03-07  5684.843510  6794.968489
        2023-03-08  5765.414060  7017.486925
...                         ...          ...
RD_F_J  2023-03-27   910.281571  1100.779747
        2023-03-28   929.252761  1151.268497
        2023-03-29   951.281082  1155.769140
        2023-03-30   941.070211  1171.089959
        2023-03-31   924.300772  1148.115289

[1092 rows x 10 columns]

In [44]:
sub = pd.read_csv('/kaggle/input/vegtablae-2023/sample_submission.csv')
sub['answer'] = np.array(result['mean'])

# 0보다 작은 친구들은 0으로 제출
sub.loc[sub['answer']<0,'answer']=0

sub.to_csv('sub.csv',index=False)

In [45]:
sub

                   ID       answer
0     TG_A_J_20230304  3364.390663
1     TG_A_J_20230305   582.941491
2     TG_A_J_20230306  3196.752489
3     TG_A_J_20230307  3591.196311
4     TG_A_J_20230308  3478.091449
...               ...          ...
1087  RD_F_J_20230327   531.921919
1088  RD_F_J_20230328   553.457134
1089  RD_F_J_20230329   556.299801
1090  RD_F_J_20230330   547.540408
1091  RD_F_J_20230331   526.231542

[1092 rows x 2 columns]